### ISSUE TITLE
add other shells

### ISSUE THREAD

**Issue by fries1234** [SomethingGeneric/GamerbotAgain#14]
like add other shells like zsh or nushell with cmds like /zsh or /nu.....

**Comment by SomethingGeneric** [comment]
and context menu option to i'd assume yea?

**Comment by fries1234** [comment]
yeah that would be cool

**Comment by SomethingGeneric** [comment]
so i'm thinking:
- `zsh`
- `fish`
- `nushell`
- `xonsh`

other ideas?

**Comment by SomethingGeneric** [comment]
gonna leave it as "not rn"
