### ISSUE TITLE
Change username directories to UUIDS

### ISSUE THREAD

**Issue by HyperStandard** [SomethingGeneric/GamerbotAgain#21]
my suggestion is to make the user directories formatted as "user_[UUID number]" so that no one can spoof another account (root or otherwise), and if a user wants to make their directory "personalized" make a /nickname or something command to change from user_111~ to e.g. amelia_111~. Presumably by either renaming the user (is that a thing) or just remaking it. And if it checks only the UUID it shouldn't really matter what the front name part is as long as its maybe just ascii chars no whitepsace or whatever is allowed in usernames/foldernames

**Comment by SomethingGeneric** [comment]
It worked! Can't really be assed to do renames lmao
