### ISSUE TITLE
Update PRIVACY document

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/GamerbotAgain#5]
Replace the signature at the end with
```
Goober.Cloud
matt[at]goober[dot]cloud
```

**Comment by therattestman** [comment]
It appears we're still encountering the same issue. The error suggests that the base branch might either be incorrect or there's another configuration causing it to be invalid.

Given this, it would be helpful to manually create the pull request from your GitHub interface. Here’s a summary of what was done:

### Summary of Changes
- Updated the `PRIVACY` document with the new contact information:
  ```
  Goober.Cloud
  matt[at]goober[dot]cloud
  ```

### Commit Details
- **Commit Message:** `Update PRIVACY document with new contact information`
- **Branch:** `therattestman:main`

From here, you can manually create the Pull Request on GitHub by comparing the changes from your forked branch (`therattestman:main`) to the original repository’s `main` branch.

Would you like further assistance with anything else?
