### ISSUE TITLE
Refactor PRIVACY and TERMS

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/GamerbotAgain#6]
Both documents refer to GoombaLabs, where they should refer to Goober.Cloud
If there's contact information, ensure it says `matt[at]goober[dot]cloud`

Thanks!

**Comment by therattestman** [comment]
An error occurred: Error code: 400 - {'error': {'message': "Expected tool outputs for call_ids ['call_sXXxv0JqXNWvlKcddyL9DgGm', 'call_PbSe3x68McDLmcE2yFIKI3Sy'], got ['call_sXXxv0JqXNWvlKcddyL9DgGm']", 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by SomethingGeneric** [comment]
i would appreciate the help!

**Comment by SomethingGeneric** [comment]
please help with this!

**Comment by therattestman** [comment]
An error occurred: Error code: 400 - {'error': {'message': "Expected tool outputs for call_ids ['call_Hea7DSpMVhG0BANoVyA1rvjg', 'call_96CwayHLY0d3QQL4BaY7EJao'], got ['call_Hea7DSpMVhG0BANoVyA1rvjg']", 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by SomethingGeneric** [comment]
pls!

**Comment by therattestman** [comment]
An error occurred: Error code: 400 - {'error': {'message': "Expected tool outputs for call_ids ['call_KwRVoJy8s8rgxkbIkuBQydaB', 'call_CHcDrXPzGCpvakMwcVE79G8f'], got ['call_KwRVoJy8s8rgxkbIkuBQydaB']", 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by SomethingGeneric** [comment]
:D

**Comment by therattestman** [comment]
An error occurred: Error code: 400 - {'error': {'message': "Expected tool outputs for call_ids ['call_CEsD0wyIe3osaQGhcuoKefnK', 'call_7mIhZuSoSeRFGecYckpK4JE7'], got ['call_CEsD0wyIe3osaQGhcuoKefnK']", 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by SomethingGeneric** [comment]
help!

**Comment by therattestman** [comment]
An error occurred: Error code: 400 - {'error': {'message': "Expected tool outputs for call_ids ['call_IB5wtWnobmsSEoovZTlOH9V0', 'call_93TAk4eIuLIgo4xqENBhAahq'], got ['call_IB5wtWnobmsSEoovZTlOH9V0']", 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by SomethingGeneric** [comment]
please take a look and update these files! :)

**Comment by SomethingGeneric** [comment]
please have a look at these files

**Comment by SomethingGeneric** [comment]
please!

**Comment by SomethingGeneric** [comment]
pls

**Comment by SomethingGeneric** [comment]
can you please have a look at this issue

**Comment by SomethingGeneric** [comment]
please!

**Comment by SomethingGeneric** [comment]
pls

**Comment by SomethingGeneric** [comment]
pls

**Comment by SomethingGeneric** [comment]
help

**Comment by SomethingGeneric** [comment]
please fix!

**Comment by SomethingGeneric** [comment]
pls

**Comment by therattestman** [comment]
No messages found in the run.

**Comment by SomethingGeneric** [comment]
pls!

**Comment by SomethingGeneric** [comment]
help

**Comment by therattestman** [comment]
It looks like there are no PDF or DOC files in the repository either. Given that we've searched for the terms "GoombaLabs," "PRIVACY," and "TERMS" without success, it's possible that the documentation may not be included in this repository at all or is stored in a different format or location.

Here's what I can do next:
1. Confirm with you if you have any specific files or directories in mind where these privacy and terms documents may be located.
2. If you have documentation in another repository or location, let me know so I can assist in making the necessary changes based on that content.

Please provide any additional information that can help locate the desired files!

**Comment by SomethingGeneric** [comment]
The files are literally named `PRIVACY` and `TERMS`, and should be in the base directory of this repository

**Comment by therattestman** [comment]
I've successfully updated the `PRIVACY` and `TERMS` documents:

1. **Refactored the references** from **Goomba Labs** to **Goober.Cloud**.
2. **Updated the contact information** to: 
   ```
   matt[at]goober[dot]cloud
   ```

These changes have been committed and pushed to your forked repository. 

### Pull Request Information
I created a pull request for these changes which you can review and merge. You can view the pull request here: [Refactor PRIVACY and TERMS](https://github.com/SomethingGeneric/GamerbotAgain/pull/9).

Feel free to take a look and let me know if any further changes are needed!

**Comment by SomethingGeneric** [comment]
Done!

**Comment by therattestman** [comment]
Great! I'm glad to hear that the pull request is completed. If you need any further assistance or have more tasks in the future, feel free to reach out. Good luck with your project! 🎉
